name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: hacanand
          password: dckr_pat_8r88WN85Mf1VEQ9Hwe3i2lrRCy4
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: hacanand/spark-delta:3.5.3